apiVersion: v1
kind: Secret
metadata:
  name: akilli-sinif-secret
  namespace: {{ include "akilli-sinif.namespace" . }}
  labels:
    {{- include "akilli-sinif.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  GEMINI_API_KEY:    {{ .Values.secret.geminiApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  username:          "appuser"
  password:          {{ .Values.secret.postgresPassword | quote }}